version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173" # Mapea el puerto 5173 del contenedor al puerto 3000 en tu máquina
    volumes:
      - .:/app # Sincroniza el código local con el directorio /app en el contenedor
      - /app/node_modules # Evita que los node_modules se sobrescriban
    command: ["npm", "run", "dev"]
